### ISSUE TITLE
Create an option to list all mdown notes instead of “recent”

### ISSUE THREAD

**Issue by cw123hb** [idkclub/Markology#4]
Please include an option to list all markdown documents instead of just most recent. This is a limitation on an overwise awesome app.

**Comment by bmetitiri** [comment]
Are you requesting that the side/root menu be able to display all notes? This would push the New Note button very far down, is that what you would expect? Or are you envisioning a "See All" button in the menu that would open a list of all the notes?

Also, a workaround in the current version is to search for the empty string (you have to press Enter/Search on the keyboard). That will display all notes, with their bodies expanded, instead of just titles.

**Comment by arkie** [comment]
(clicking on the Most Recent header to toggle should now work in the latest release 👍 )

**Comment by cw123hb** [comment]
The latest release solved the issue.
